a = "Sumedho Ariya Herdaya"
b = (29-1)
c = (100.7)
d = (2+0j)
e = ("alpro", "strukDat", "arsikom")
f = ["alpro", "strukDat", "arsikom"]
g = range(9)
h = {"nama" : "Sumedho Ariya Herdaya", "NIM" : "25071207230"}
i = {"alpro", "strukDat", "arsikom"}
j = frozenset({"alpro", "strukDat", "arsikom"})
k = False
l = b"Sumedho"
m = bytearray(9)
n = memoryview(bytes(9))
o = None
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(f))
print(type(g))
print(type(h))
print(type(i))
print(type(j))
print(type(k))
print(type(l))
print(type(m))
print(type(n))
print(type(o))

#Setting Specific Data Type
A = str("Sumedho Ariya Herdaya")
B = int(29-1)
C = float(100.7)
D = complex(2+0j)
E = list(("alpro", "strukDat", "arsikom"))
F = tuple(("alpro", "strukDat", "arsikom"))
G = range(9)
H = dict(nama = "Sumedho Ariya Herdaya", NIM = 25071207230)
I = set(("alpro", "strukDat", "arsikom"))
J = frozenset(("alpro", "strukDat", "arsikom"))
K = bool(0)
L = bytes(7)
M = bytearray(9)
N = memoryview(bytes(9))

print(type(A))
print(type(B))
print(type(C))
print(type(D))
print(type(E))
print(type(F))
print(type(G))
print(type(H))
print(type(I))
print(type(J))
print(type(K))
print(type(L))
print(type(M))
print(type(N))